### PR TITLE
fix: allow reap/fight actions to select exhausted targets

### LINKED ISSUE #3954: Shock Herder doesn't allow you to select Awakened Titan
I played Shock Herder from hand and deployed it between an Awakened Titan and another creature. I was not haunted and couldn't ready Awakened Titan, but TCO wouldn't even allow me to select it; it forced me to select the other creature. I should be able to select Awakened Titan, and if I'm not haunted, it simply shouldn't ready.

### PR DESCRIPTION
**Pull request by dmikalova**
fix: Allow shock herder to ready awakened titan
fix: Allow ghosthawk to select exhausted creatures
fix: alwaysTrigger typo - should be alwaysTriggers

Should fix several other cards that use sequential ready, fight/reap: Anger, Ganger Chieftain, Gauntlet of Command, Sargaent Zakiel, The Grey Rider, War Grumpus, Badgemagus, Countryside Crusher, Fancy Donavan, Razors Gambit, Bellatoran Recruit, Endurance, Honored Battlemaster, Journey Onward, Master Tashi, reap or sow, master tashi, and potentially other cards.

fixes #3954

### CODE REVIEW

File: server/game/GameActions/FightGameAction.js [hunk 1]
```diff
@@ -30,6 +32,10 @@ class FightGameAction extends CardGameAction {
         if (event.card.stunned) {
             return true;
         }
+        // Even if ignoreExhausted is set for targeting, the creature must be ready to actually fight
```
Comment (fionawhim) [inline server/game/GameActions/FightGameAction.js:34]: 👍

File: test/server/cards/01-Core/GangerChieftain.spec.js [hunk 2]
```diff
@@ -118,4 +118,32 @@ describe('Ganger Chieftain', function () {
...
+        it('on play, it should allow selecting a creature that cannot ready', function () {
+            this.player1.reap(this.awakenedTitan);
+            expect(this.awakenedTitan.exhausted).toBe(true);
+            this.player1.playCreature(this.gangerChieftain, true);
+            this.player1.clickCard(this.awakenedTitan); // click to position
+            expect(this.player1).toHavePrompt('Any reactions to Ganger Chieftain being played?');
+            this.player1.clickCard(this.gangerChieftain);
+            expect(this.player1).toBeAbleToSelect(this.awakenedTitan);
+            this.player1.clickCard(this.awakenedTitan); // click to fail ready
+            expect(this.awakenedTitan.exhausted).toBe(true);
```
Comment (fionawhim) [inline test/server/cards/01-Core/GangerChieftain.spec.js:144]: 👍

**Review by fionawhim — APPROVED** [review]

File: server/game/GameActions/FightGameAction.js [hunk 3]
```diff
@@ -20,7 +20,9 @@ class FightGameAction extends CardGameAction {
             : card.getFightAction(this.fightCardCondition);
         let newContext = fightAction.createContext(context.player);
         newContext.ignoreHouse = true;
-        if (fightAction.meetsRequirements(newContext, ['stunned'])) {
+        let ignoredRequirements = ['exhausted', 'stunned'];
+        let meetsReqResult = fightAction.meetsRequirements(newContext, ignoredRequirements);
```
Comment (strib) [inline server/game/GameActions/FightGameAction.js]: This should be a `const` (or just moved back into the `if` statement, since we don't reuse it).

File: test/server/cards/01-Core/GangerChieftain.spec.js [hunk 4]
```diff
@@ -118,4 +118,32 @@ describe('Ganger Chieftain', function () {
...
+                    inPlay: ['batdrone', 'dextre']
+                }
+            });
+        });
+
+        it('on play, it should allow selecting a creature that cannot ready', function () {
+            this.player1.reap(this.awakenedTitan);
+            expect(this.awakenedTitan.exhausted).toBe(true);
+            this.player1.playCreature(this.gangerChieftain, true);
+            this.player1.clickCard(this.awakenedTitan); // click to position
```
Comment (strib) [inline test/server/cards/01-Core/GangerChieftain.spec.js]: I don't understand this click -- Chieftain doesn't have deploy so why do we need to position it?

Comment (dmikalova) [reply test/server/cards/01-Core/GangerChieftain.spec.js]: You're right, removed

File: server/game/GameActions/FightGameAction.js (hunk 3 above)
Comment (dmikalova) [reply server/game/GameActions/FightGameAction.js]: Fixed
