### PR TITLE
Fixes QuantumFingertrap Sentry error

### LINKED ISSUE #864: Quantum Fingertrap: Cannot read property 'controller' of undefined
Sentry Issue: [KEYTEKI-GV](https://sentry.io/organizations/throneteki/issues/1325667431/?referrer=github_integration)

```
TypeError: Cannot read property 'controller' of undefined
  File "/Users/keyteki/keyteki-node2/server/game/cards/02-AoA/QuantumFingertrap.js", line 15, in SwapAction.propertyFactory
    '{snip} ap(context => ({ origin: context.targets.first, originIndex: context.targets.first.controller.cardsInPlay.indexOf(context.targets.first) }))
  File "/Users/keyteki/keyteki-node2/server/game/GameActions/SwapAction.js", line 9, in SwapAction.update
    this.applyProperties(Object.assign({ target: this.getDefaultTargets(context), origin: context.source }, this.propertyFactory(context)));
  File "/Users/keyteki/keyteki-node2/server/game/GameActions/GameAction.js", line 64, in SwapAction.hasLegalTarget
    this.update(context);
  File "/Users/keyteki/keyteki-node2/server/game/GameActions/CardGameAction.js", line 17, in SwapAction.hasLegalTarget
    let result = super.hasLegalTarget(context);
  File "/Users/keyteki/keyteki-node2/server/game/AbilityTargets/AbilityTargetCard.js", line 53, in null.<anonymous>
    return this.properties.gameAction.filter(gameAction => gameAction.hasLegalTarget(context));
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by romanogit**
Fixes #864

### CODE REVIEW

File: server/game/cards/02-AoA/QuantumFingertrap.js [hunk 1]
```diff
@@ -6,13 +6,14 @@ class QuantumFingertrap extends Card {
             targets: {
                 first: {
                     cardType: 'creature',
-                    controller: 'any'
+                    controller: 'any',
+                    cardCondition: (card) => !(card.controller.creaturesInPlay.length < 2 && (card.controller.opponent && card.controller.opponent.creaturesInPlay.length < 2))
```
Comment (cryogen) [inline server/game/cards/02-AoA/QuantumFingertrap.js]: this confuses me

Comment (romanogit) [reply server/game/cards/02-AoA/QuantumFingertrap.js]: It is unnecessary to select a card to swap if either player has 1 card each. This avoids unnecessary prompt.
It cannot be a condition in action because we can still use the artifact.

Comment (cryogen) [reply server/game/cards/02-AoA/QuantumFingertrap.js]: Can you rewrite it in a way that makes that clearer?  having a ! at the start of an expression is usually pretty confusing

Comment (romanogit) [reply server/game/cards/02-AoA/QuantumFingertrap.js]: Done
