### PR TITLE
fix: Corner the market interrupting after discard effects

### LINKED ISSUE #3558: Corner the Market + Auto-encoder
Corner the Market now says:
Play: During your opponent’s next turn, they [cannot](https://archonarcana.com/Cannot_vs_Must) play cards, and each time they discard a card from their hand, they may archive that card from their discard pile.

This is no longer a replacement effect, and when using CTM you should also archive the top of your deck if you have auto-encoder out. Currently it does not archive the top card of deck for you.

### PR DESCRIPTION
**Pull request by dmikalova**
- fix: Corner the market interrupting after discard effects - ie the old tinker or auto-encoder
- fix: CTM prompting if you make opponent discard on your turn
- Changed cancel discard to false, added a player check, and updated tests for CTM.

Should fix #3558 and #4385 and #3952

### CODE REVIEW

File: server/game/cards/06-WoE/CornerTheMarket.js [hunk 1]
```diff
@@ -42,16 +43,12 @@ class CornerTheMarket extends Card {
...
                             }))
                         })
                     ]),
-                    message: '{0} uses {1} to allow archival of {2} instead of discard',
-                    messageArgs: (context) => [
-                        context.player.opponent,
-                        context.source,
-                        context.event.card
-                    ]
+                    message: '{0} uses {1} to archive {2} from the discard pile',
```
Comment (strib) [inline server/game/cards/06-WoE/CornerTheMarket.js]: I don't like this change because it says they archive a card even when they choose to discard it. Ideally we'd only print a message when they do choose to archive it.

Comment (dmikalova) [reply server/game/cards/06-WoE/CornerTheMarket.js]: Hmm good catch, but I'm having trouble implementing this like deusillus. As it is, its before the event so I can't check the card.location. If I move it to a then: then I can't seem to find the card that was discarded. Would the solution be similar to Deusillus - just save the choice to a var?

**Review by strib — APPROVED** [review]
