### PR TITLE
fix: Mimicry and Mimic Gel copying alpha cards

### LINKED ISSUE #1839: Mimicry and Exhume should allow selecting alpha action / creature and fizzle
Mimicry and Exhume should allow selecting alpha action / creature and fizzle

Mimicry particularly if played as second card. As first card should still work.

### LINKED ISSUE #2943: Mimic Gel and Alpha Cards
Mimic gel should only be able to copy an Alpha creature as the first action of a turn. I just watched a game where that was done illegally.

https://archonarcana.com/Mimic_Gel
Can Mimic Gel be used to copy a creature with [Alpha](https://archonarcana.com/Alpha) if it is not the first card played in the step?
You cannot play Mimic Gel as a copy of a creature with [Alpha](https://archonarcana.com/Alpha) unless it is the first card you play that turn. This follows similar precedent as the [Mimicry](https://archonarcana.com/Mimicry) + [Eureka](https://archonarcana.com/Eureka) examples in the FAQ.

Relevant log.
TURN 9 - X
Key phase - X
X does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - X
X chooses logos  as their active house this turn
Main phase - X
X plays Information Exchange
X uses Information Exchange to steal 2 Æmber  from Y
X  plays Wild Wormhole
X gains an Æmber  due to Wild Wormhole's bonus icon
X uses Wild Wormhole to play Chief Engineer Walls
X plays Chief Engineer Walls
X uses Chief Engineer Walls to return C.Æ.N.D.L.E. Unit to their hand
X plays Thorium Plasmate
X gains an Æmber  due to Thorium Plasmate's bonus icon
X uses Thorium Plasmate to move Information Officer Gray on Y battleline and deal 2 damage to it for each neighbor that shares a house with it
X uses Mimic Gel to to copy Gargantes Scrapper
X uses Gargantes Scrapper to deal 3 damage to Sensor Chief Garcia

### PR DESCRIPTION
**Pull request by dmikalova**
fix: Mimicry and Mimic Gel copying alpha cards - fixes #2943, fixes #1839

### CODE REVIEW

File: server/game/GameActions/PlayCardAction.js [hunk 1]
```diff
@@ -57,7 +57,13 @@ class PlayCardAction extends CardGameAction {
             .getActions(this.location)
             .filter((action) => action.title.includes('Play'));
 
-        return playActions.some((action) => this.actionMeetsRequirement(event.context, action));
+        const hasValidPlayAction = playActions.some((action) =>
+            this.actionMeetsRequirement(event.context, action)
+        );
+
+        // If revealOnIllegalTarget is true, allow the event to proceed even without valid play actions
```
Comment (dmikalova) [inline server/game/GameActions/PlayCardAction.js:64]: This allows Bot Bookton to message:

```
2026-01-27 19:45:07 player1 uses Bot Bookton to reap with Bot Bookton
2026-01-27 19:45:07 player1 uses Bot Bookton to play Eureka!
2026-01-27 19:45:07 player1 is unable to play Eureka! and returns it to deck
```

File: server/game/GameActions/PutIntoPlayAction.js [hunk 2]
```diff
@@ -48,6 +48,13 @@ class PutIntoPlayAction extends CardGameAction {
             return;
         }
 
+        // Check if creature should go to a different location instead of play area
```
Comment (dmikalova) [inline server/game/GameActions/PutIntoPlayAction.js]: This allows Mimic Gel to message:

```
2026-01-27 19:48:43 player1 uses Batdrone to reap with Batdrone
2026-01-27 19:48:43 player1 uses Mimic Gel to copy Bumblebird
2026-01-27 19:48:43 player1 plays Mimic Gel as Bumblebird
2026-01-27 19:48:43 player1 is unable to play Mimic Gel as Bumblebird and returns it to hand
```

File: server/game/GameActions/PutIntoPlayAction.js [hunk 3]
```diff
@@ -283,6 +290,22 @@ class PutIntoPlayAction extends CardGameAction {
                         .resolve(card, context);
                 }
 
+                // Show play message
+                context.game.addMessage('{0} plays {1}', player, card);
```
Comment (dmikalova) [inline server/game/GameActions/PutIntoPlayAction.js:294]: This logs the plays message:

```
2026-01-27 20:49:38 player1 uses Mimic Gel to copy Bumblebird
2026-01-27 20:49:38 player1 plays Mimic Gel as Bumblebird
2026-01-27 20:49:38 player1 is unable to play Mimic Gel as Bumblebird and returns it to hand
```

File: server/game/BaseActions/PlayAction.js [hunk 4]
```diff
@@ -6,12 +6,28 @@ class PlayAction extends BasePlayAction {
         this.title = 'Play this action';
     }
 
+    displayMessage(context) {
+        super.displayMessage(context);
```
Comment (dmikalova) [inline server/game/BaseActions/PlayAction.js:10]: This logs the plays message, and next the unable play:

```
2026-01-27 20:52:51 player1 uses Ancient Bear to reap with Ancient Bear
2026-01-27 20:52:51 player1 uses Mimicry to copy Binate Rupture
2026-01-27 20:52:51 player1 plays Mimicry as Binate Rupture
2026-01-27 20:52:51 player1 is unable to play Mimicry as Binate Rupture and returns it to hand
```

File: server/game/BaseActions/PlayCreatureAction.js [hunk 5]
```diff
@@ -7,6 +7,11 @@ class PlayCreatureAction extends BasePlayAction {
         this.deploy = false;
     }
 
+    displayMessage() {
```
Comment (dmikalova) [inline server/game/BaseActions/PlayCreatureAction.js:10]: This suppresses the double play message:

```
2026-01-27 20:54:45 player1 uses Batdrone to reap with Batdrone
2026-01-27 20:54:45 player1 uses Mimic Gel to copy Bumblebird
2026-01-27 20:54:45 player1 plays Mimic Gel as Bumblebird
2026-01-27 20:54:45 player1 plays Mimic Gel as Bumblebird
2026-01-27 20:54:45 player1 is unable to play Mimic Gel as Bumblebird and returns it to hand
```

File: server/game/GameActions/PlayCardAction.js [hunk 6]
```diff
@@ -57,7 +57,13 @@ class PlayCardAction extends CardGameAction {
...
+        // so we can show an appropriate message
+        return hasValidPlayAction || this.revealOnIllegalTarget;
```
Comment (dmikalova) [inline server/game/GameActions/PlayCardAction.js:66]: This logs the play message:

```
2026-01-27 20:57:55 player1 uses Bot Bookton to reap with Bot Bookton
2026-01-27 20:57:55 player1 uses Bot Bookton to play Eureka!
2026-01-27 20:57:55 player1 is unable to play Eureka! and returns it to deck
```

File: server/game/GameActions/PlayCardAction.js [hunk 7]
```diff
@@ -87,8 +93,10 @@ class PlayCardAction extends CardGameAction {
                     event.illegalTarget = true;
                     if (this.revealOnIllegalTarget) {
                         context.game.addMessage(
-                            '{0} was unable to be played so is returned to its original location',
-                            card
+                            '{0} is unable to play {1} and returns it to {2}',
```
Comment (dmikalova) [inline server/game/GameActions/PlayCardAction.js:96]: This logs the unable to play message:

```
2026-01-27 20:57:55 player1 uses Bot Bookton to reap with Bot Bookton
2026-01-27 20:57:55 player1 uses Bot Bookton to play Eureka!
2026-01-27 20:57:55 player1 is unable to play Eureka! and returns it to deck
```

File: server/game/GameActions/PutIntoPlayAction.js [hunk 8]
```diff
@@ -42,12 +42,19 @@ class PutIntoPlayAction extends CardGameAction {
...
+        const card = this.target.length > 0 ? this.target[0] : context.source;
 
         if (card.gigantic && !this.canPutIntoPlayGigantic(context, card)) {
             return;
         }
 
+        // Check if creature should go to a different location instead of play
+        // area - eg Mimic Gel and Alpha. If so, skip flank selection.
+        const redirectLocation = card.mostRecentEffect('cardLocationAfterPlay');
+        if (redirectLocation && redirectLocation !== 'play area') {
```
Comment (dmikalova) [inline server/game/GameActions/PutIntoPlayAction.js:54]: This logs the unable to play message:

```
2026-01-27 20:49:38 player1 uses Mimic Gel to copy Bumblebird
2026-01-27 20:49:38 player1 plays Mimic Gel as Bumblebird
2026-01-27 20:49:38 player1 is unable to play Mimic Gel as Bumblebird and returns it to hand
```

**Review by strib — APPROVED** [review]
