### PR TITLE
fix: prevent steal messaging

### LINKED ISSUE #1026: [display bug] Aember is logged as stolen even when stealing is prevented
I just had a turn where I forgot to use Snudge to return my opponent's Odarc before playing Shooler.  This is the log from that turn.

> Main phase - hyramgraff
hyramgraff uses Dust Imp to make Dust Imp fight Kompsos Haruspex
hyramgraff uses Dust Imp to gain 2 Æmber 
hyramgraff plays Shooler
hyramgraff uses Shooler to steal 1 Æmber  from animal
hyramgraff uses Snudge to reap with Snudge
hyramgraff uses Snudge to return Odoac the Patrician to their hand
hyramgraff uses Ember Imp to reap with Ember Imp
hyramgraff uses Pitlord to make Pitlord fight Armsmaster Molina
animal uses Armsmaster Molina to deal 3 damage to Pitlord

The steal that would normally happen from Shooler was logged (opponent was on six aember) even though the steal didn't actually happen.

### PR DESCRIPTION
**Pull request by dmikalova**
fix: prevent steal messaging - fixes #1026

Updated the messaging to interleave sequential effects with the effects message

Before draw, steal, draw:
```
2026-02-04 22:59:35 player1 plays Closed-Door Negotiation
2026-02-04 22:59:35 player1 gains an amber due to Closed-Door Negotiation's bonus icon
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to draw 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:59:35 player2 draws 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to draw 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:59:35 player2 draws 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to draw 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:59:35 player2 draws 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to draw 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:59:35 player2 draws 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to draw 1 card
2026-02-04 22:59:35 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:59:35 player2 draws 1 card
```

After: draw, draw, steal
```
2026-02-04 22:56:51 player1 plays Closed-Door Negotiation
2026-02-04 22:56:51 player1 gains an amber due to Closed-Door Negotiation's bonus icon
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to make player2 draw 1 card
2026-02-04 22:56:51 player2 draws 1 card
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to make player2 draw 1 card
2026-02-04 22:56:51 player2 draws 1 card
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to make player2 draw 1 card
2026-02-04 22:56:51 player2 draws 1 card
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to make player2 draw 1 card
2026-02-04 22:56:51 player2 draws 1 card
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to steal 1 amber from player2
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to make player2 draw 1 card
2026-02-04 22:56:51 player2 draws 1 card
2026-02-04 22:56:51 player1 uses Closed-Door Negotiation to steal 1 amber from player2
```

Before: steals
```
2026-02-04 23:00:39 player1 plays Urchin
2026-02-04 23:00:39 player1 uses Urchin to steal 1 amber from player2
```

After: Steal, prevents
```
2026-02-04 23:01:10 player1 plays Urchin
2026-02-04 23:01:10 player1 uses Urchin to steal 1 amber from player2
2026-02-04 23:01:10 player2 uses Odoac the Patrician to prevent Urchin from stealing amber
```

### CODE REVIEW

File: server/game/GameActions/DrawAction.js [hunk 1]
```diff
@@ -6,12 +6,29 @@ class DrawAction extends PlayerAction {
         this.amount = 1;
         this.refill = false;
         this.bonus = false;
+        this.effectMsg = null;
     }
 
     setup() {
         super.setup();
         this.name = 'draw';
```
Comment (dmikalova) [inline server/game/GameActions/DrawAction.js:14]: Originally for closed door it was "player1 draws a card" and now it updates based on target

File: server/game/GameActions/StealAction.js [hunk 2]
```diff
@@ -21,6 +21,40 @@ class StealAction extends PlayerAction {
         );
     }
```
Comment (dmikalova) [inline server/game/GameActions/StealAction.js:23]: If the even is prevented by an effect, the print that after the effect

File: server/game/GameActions/DrawAction.js [hunk 3]
```diff
@@ -6,12 +6,29 @@ class DrawAction extends PlayerAction {
...
-        this.effectMsg = 'draw ' + this.amount + ' card' + (this.amount > 1 ? 's' : '');
+        this.customEffectMsg = this.effectMsg;
+        // Default effectMsg set here, may be updated in update() based on target
+        this.effectMsg = `draw ${this.amount} card${this.amount > 1 ? 's' : ''}`;
+    }
+
+    update(context) {
```
Comment (dmikalova) [inline server/game/GameActions/DrawAction.js:20]: Closed door has an event message - "make player2 draw a card". This prints that. Then the above regular message is printed "player2 draws a card.

This is a bit verbose, but without hyper custom logic to handle messaging, it seems better to just log everything as it happens, in the expected order. eg log "1 uses card to make 2 do y", then log "2 does y" is a lot easier to consistently template across the system bc it splits the what the effect does, and the what happens.

File: server/game/CardAbility.js [hunk 4]
```diff
@@ -6,6 +6,87 @@ class CardAbility extends ThenAbility {
 
         this.location = properties.location || 'play area';
         this.printedAbility = properties.printedAbility === false ? false : true;
+
```
Comment (dmikalova) [inline server/game/CardAbility.js:9]: This interleaves the messages, rather than puts them after the sequential message. eg closed door does a [draw, steal] with a makes x do y message - previously that printed makes x do y, steal, then draw, and now it does makes x do y, draw, steal

File: server/game/CardAbility.js [hunk 5]
```diff
@@ -82,75 +163,83 @@ class CardAbility extends ThenAbility {
         }
 
         if (this.properties.message) {
```
Comment (dmikalova) [inline server/game/CardAbility.js:138]: Flatten the nested logic of the rest of the file

File: test/helpers/integrationhelper.js [hunk 6]
```diff
@@ -348,7 +348,7 @@ beforeEach(function () {
 });
 
 afterEach(function () {
-    if (process.env.DEBUG_TEST) {
+    if (process.env.DEBUG_TEST && this.game?.getPlainTextLog) {
```
Comment (dmikalova) [inline test/helpers/integrationhelper.js:351]: If you run debug logs on the full test suite this crashes.

File: server/game/CardAbility.js [hunk 7]
```diff
@@ -6,6 +6,87 @@ class CardAbility extends ThenAbility {
...
+            this.game.openEventWindow(events);
+        }
+
+        // Queue the next action
+        this.game.queueSimpleStep(() =>
+            this.executeNextAction(actions, context, index + 1, allEvents)
+        );
+    }
+
+    handleThenAbilities(context, actions, allEvents) {
```
Comment (strib) [inline server/game/CardAbility.js:59]: Would like to see this share code with ThenAbility.executeGameActions in a less duplicatey way.

**Review by strib — APPROVED** [review]
