### PR TITLE
fix: Badger should trigger after playing Badger

### LINKED ISSUE #4644: Badger does not deal damage for itself
When badger is played it should deal 3 damage to an enemy creature, but it does not.

### PR DESCRIPTION
**Pull request by dmikalova**
fix: Badger should trigger after playing Badger - fixes #4644

### CODE REVIEW

File: server/game/cards/13-CC/Badger.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ class Badger extends Card {
                 when: {
                     onCardPlayed: (event) =>
                         event.player === context.player &&
-                        event.card !== context.source &&
+                        // event.card !== context.source &&
```
Comment (strib) [inline server/game/cards/13-CC/Badger.js]: Can nuke this line.

**Review by strib — APPROVED** [review]
