### PR TITLE
Mimicry fixes and tests

### LINKED ISSUE #391: Mimicry into Phloxem Spike does nothing
I played Mimicry to copy Phloxem Spike. I had no creatures in play, my oponent had 5. Nothing happened, so apparently, it doesn't work the way it should.

### LINKED ISSUE #1071: Mimicry + Swindle
Opponent played Mimicry. Copied my Swindle. Profited.

### LINKED ISSUE #1940: Mimicry + Commune
Mimicry when copying commune does not trigger omega allowing for additional actions to be taken, cards to be played.

### PR DESCRIPTION
**Pull request by romanogit**
Fixes #1071 Mimicry / Swindle (aka Mimicry and omega cards)
Fixes #391 Mimicry and Phloxem Spike

Added test case to:
#861 Mimicry + Information Exchange not stealing 2 - working as expected
#615 Mars needs aember and mimicry dysfunctionality - working as expected
#1152 City-state Interest, Mimicry/City-state Interest doesn't capture - working as expected

#667 Murkens and Mimicry - added a xit test case, but still unable to fix (removed - should be a Murkens test)

Fixes  #1940 as well Mimicry and Comune

Added a test case for playing alpha when card was already used. It is failing.

### CODE REVIEW

File: server/game/cards/02-AoA/PhloxemSpike.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ class PhloxemSpike extends Card {
     setupCardAbilities(ability) {
         this.play({
             effect: 'destroy each creature not on a flank.',
-            condition: () => this.controller.creaturesInPlay.length === 0,
+            condition: (context) => context.game.activePlayer.creaturesInPlay.length === 0,
```
Comment (jeremylarner) [inline server/game/cards/02-AoA/PhloxemSpike.js:7]: This should probably be `context.player`, although I can't think of any situation where it might matter....

Comment (romanogit) [reply server/game/cards/02-AoA/PhloxemSpike.js]: Fixed

**Comment by romanogit** [comment]
It does not fix perfectly alpha yet, but at least fixes Omega.
I think it superseedes #1143

**Comment by romanogit** [comment]
Hello @cryogen , any issue with this Mimicry change?
It fixes the Omega problem with Mimicry.
