### PR TITLE
Fixes a few game messages. Using targetting instead of promptForSelect

### LINKED ISSUE #1082: Bouncing Deathquark message when player has no creature is incomplete [cosmetic]
Message has a lingering `and` when the player of BD has not creature.

`GavinForge uses Bouncing Deathquark to destroy Sensor Chief Garcia and `

### LINKED ISSUE #1091: The Floor is Lava's message misses targets [cosmetic]
`xxx uses The Floor is Lava to deal 1 damage to The Floor is Lava`

### LINKED ISSUE #1104: Giant Gnawbill message prints incorrect target [cosmetic]
`riffyD uses Giant Gnawbill to destroy Giant Gnawbill`

Should say which artifact was destroyed.

### PR DESCRIPTION
**Pull request by romanogit**
Fixes #1104
Fixes #1091
Fixes #1082

### CODE REVIEW

File: server/game/cards/01-Core/BouncingDeathQuark.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ class BouncingDeathquark extends Card {
                 }
             },
             effect: 'destroy {1}',
-            effectArgs: context => [[context.targets.enemy, context.targets.friendly]],
+            effectArgs: context => [Object.values(context.targets)],
```
Comment (cryogen) [inline server/game/cards/01-Core/BouncingDeathQuark.js]: Why do we have arrays in arrays? that can't be right
