### PR TITLE
Fixed glowing (can-play) while selected

### LINKED ISSUE #665: Selection of glowing cards in hand is confusing (UI)
When I play `Song of Spring` and want to select a creature in my hand that could still be played or discarded, the glowing effect of "selectable to play" and the glowing effect of "selected" are confusing. 

I missed returning a card because I thought it was selected and it was actually not.

### LINKED ISSUE #998: Unnatural Selection card highlighting inconsistent with ready Untamed cratrues
Apparently, when you use Unnatural Selection to select the creatures on your side you want to preserve from destruction, when you select off-house creatures they are highlighted with a solid green frame like normal, but when you select a ready untamed creature, it highlights it with the golden, pulsing, 'available-for-selection' frame, not the green 'has been selected' frame.

### PR DESCRIPTION
**Pull request by romanogit**
Cleaned up some card status that are not applicable to KF
Fixes #665
Fixes #998

### CODE REVIEW

File: client/Components/GameBoard/Card.jsx [hunk 1]
```diff
@@ -315,12 +315,6 @@ class InnerCard extends React.Component {
             return 'selected';
         } else if(this.props.card.selectable) {
             return 'selectable';
-        } else if(this.props.card.inDanger) {
-            return 'in-danger';
-        } else if(this.props.card.saved) {
-            return 'saved';
-        } else if(this.props.card.new) {
```
Comment (cryogen) [inline client/Components/GameBoard/Card.jsx]: This should be restored, it's supposed to be used, but is broken atm

File: client/Components/GameBoard/Card.jsx [hunk 2]
```diff
@@ -357,14 +351,11 @@ InnerCard.propTypes = {
         facedown: PropTypes.bool,
         factionStatus: PropTypes.array,
         image: PropTypes.string,
-        inDanger: PropTypes.bool,
         exhausted: PropTypes.bool,
         menu: PropTypes.array,
         name: PropTypes.string,
-        new: PropTypes.bool,
```
Comment (cryogen) [inline client/Components/GameBoard/Card.jsx]: this too
