### PR TITLE
fix: Dark Discovery messaging

### LINKED ISSUE #4870: Misleading logs from "Drawn Down"
Image

The log implies that a player is adding an opponent's card their hand, which is clearly not how the card actually works.

### PR DESCRIPTION
**Pull request by dmikalova**
fix: Dark Discovery messaging - fixes #4870 

```
2026-02-06 23:03:00 player1 plays Dark Discovery
2026-02-06 23:03:00 player1 gains an amber due to Dark Discovery's bonus icon
2026-02-06 23:03:00 player1 uses Dark Discovery to name Gub and Krump
2026-02-06 23:03:00 player1 uses Dark Discovery to discard Krump and Gub
2026-02-06 23:03:00 player1 purges Dark Discovery and forges a key at no cost
2026-02-06 23:03:00 player1 forges the forgedkeyred, paying 0 amber
```

```
2026-02-06 23:03:27 player1 plays Dive Deep
2026-02-06 23:03:27 player1 uses Dive Deep to discard Troll
2026-02-06 23:03:27 player1 uses Dive Deep to put Krump on the bottom of player2's deck
```

```
2026-02-06 23:03:53 player1 plays Drawn Down
2026-02-06 23:03:53 player1 uses Drawn Down to look at the top 3 cards of player2's deck
2026-02-06 23:03:53 player1 uses Drawn Down to discard Gub
2026-02-06 23:03:53 player1 uses Drawn Down to put a card on the bottom of player2's deck
2026-02-06 23:03:53 player1 uses Drawn Down to put a card to the top of player2's deck
```

### CODE REVIEW

File: server/game/cards/05-DT/DrawnDown.js [hunk 1]
```diff
@@ -1,26 +1,49 @@
...
+                                message: "{0} uses {1} to put a card on the bottom of {3}'s deck",
+                                messageArgs: [context.player.opponent]
+                            }
+                        };
+                    })
+                })
+            ]),
+            then: {
+                alwaysTriggers: true,
+                condition: (context) => context.player.opponent.deck.length >= 3,
```
Comment (strib) [inline server/game/cards/05-DT/DrawnDown.js]: Is this right?  Shouldn't it be `>= 2`, since before the `then` you already discarded one card?

File: server/game/cards/05-DT/DrawnDown.js [hunk 2]
```diff
@@ -1,26 +1,49 @@
...
+                        return {
+                            promptWithHandlerMenu: {
+                                activePromptTitle: 'Choose a card to discard',
+                                cards: cards
+                            }
+                        };
+                    })
+                }),
+                ability.actions.conditional({
+                    condition: (context) => context.player.opponent.deck.length >= 2,
```
Comment (strib) [inline server/game/cards/05-DT/DrawnDown.js]: Not sure about this -- is the condition evaluated before the first card is discarded, or after?  If after, this should be `>= 1`.

**Review by strib — COMMENTED** [review]
Could use some new tests for exactly 2- and 3-card decks.

**Review by strib — APPROVED** [review]
