### PR TITLE
fix: 2 bugs around flipping cards

### LINKED ISSUE #3957: Temporal purge returns aember
When temporal purge is used to flip a token creature, and the card that is flipped is an action, any aember on that card should return to the common supply instead of returning as captured aember because captured aember only returns when a creature is removed from play.

Currently TCO returns the aember.

### PR DESCRIPTION
**Pull request by fionawhim**
Fixes #3957

This fixes 2 bugs with flipping cards:

- Prevents token creatures given Gĕzdrutyŏ the Arcane’s ability from flipping face up, based on [this Sanctumonious Discord discussion](https://discord.com/channels/563737400275107920/588586239997902858/1455295375454896311) that came to the consensus that “flip facedown” meant “physically the card face down” rather than “flip to the other side.”
- Flips cards and returns them to their printed type before discarding them when they’re not creatures. Makes it so that æmber captured on a token creature that’s an action on the other side goes to the common supply when Temporal Purge is played.

(Includes a new test on De-Animator to ensure that its current behavior, which considers the current type of the card — artifact — rather than the printed type — creature — for æmber when it’s destroyed.)

### CODE REVIEW

File: server/game/GameActions/FlipAction.js [hunk 1]
```diff
@@ -11,6 +16,7 @@ class FlipAction extends CardGameAction {
     canAffect(card, context) {
         return (
             card.location === 'play area' &&
+            (this.direction === 'any' || (this.direction === 'face-down' && !card.isToken())) &&
```
Comment (dmikalova) [inline server/game/GameActions/FlipAction.js]: Might it make sense to also add `face-up` since temporal purge references? I don't think there's any situation at the moment where its relevant, but just for completeness

File: test/server/cards/08-AS/DeAnimator.spec.js [hunk 2]
```diff
@@ -145,5 +145,20 @@ describe('De-Animator', function () {
             expect(this.botBookton.location).toBe('discard');
             expect(this.player1).toHavePrompt('Choose a card to play, discard or use');
         });
+
+        it('should send æmber on destroyed mineralized creatures to the common supply', function () {
```
Comment (dmikalova) [inline test/server/cards/08-AS/DeAnimator.spec.js]: nit: mineralized doesn't exactly mean anything in the game - creatures can have a mineralize counter on them, and if de-animator is out then the creatures with a mineralize counter are artifacts. But if de-animator is not out then they're still creatures.

Might be more accurate to say "destroyed creatures as artifacts" or something similar.

**Review by dmikalova — APPROVED** [review]
Looks good, just some small nits

File: server/game/GameActions/FlipAction.js (hunk 1 above)
Comment (fionawhim) [reply server/game/GameActions/FlipAction.js]: Makes sense!

File: test/server/cards/08-AS/DeAnimator.spec.js (hunk 2 above)
Comment (fionawhim) [reply test/server/cards/08-AS/DeAnimator.spec.js]: Done.
