### PR TITLE
Fixes Epic Quest after used by Nexus - bug in conditional action for PlayerAction

### LINKED ISSUE #2098: Epic Quest forging for opponent
image

So, this happened. I used Epic Quest and it forged a key for my opponent, winning him the game. Maybe something to do with the fact he used Nexus two turns before in order to prevent me from winning?

### PR DESCRIPTION
**Pull request by romanogit**
Fixes #2098

### CODE REVIEW

File: server/game/cards/03-WC/Memolith.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ class Memolith extends Card {
                     card.location === 'hand' ||
                     (card.parent === context.source && card.location === 'grafted'),
                 gameAction: ability.actions.conditional({
-                    condition: (context) => context.target.location === 'hand',
+                    condition: (context) => context.target && context.target.location === 'hand',
```
Comment (cryogen) [inline server/game/cards/03-WC/Memolith.js:14]: target should never be undefined here, if it is, I'd rather it blow up because it's a bug in the engine
