### PR TITLE
fix: implement both player discard ordering

### LINKED ISSUE #3867: Curse of spontaneity does not prompt you the order you would like to discard your cards in.
This is important since the order of your discard piles matters a lot in this set.

### LINKED ISSUE #4662: Trihard should allow you to choose which player discards first
Trihard is currently implemented such that player and then opponent discard - however for simultaneous discard the active player is able to choose.

Recklessness is implemented differently, but I suspect it has the same issue. Should also check other cards that cause both players to discard.

### PR DESCRIPTION
**Pull request by dmikalova**
fix: implement both player discard ordering - fixes #3867 and fixes #4662 
feat: Add discardEntireLocation - this handles discarding until the targeted zone has no more cards.
feat: Add discardRandomCardsToAmount - this handles catch and release with scrap effects
fix: Active player now choooses who discards first if both players are discarding
fix: Active player can now choose the order of their discards or autoresolve. Opponent's hand is always discarded randomly.

Logs for discard location:
```
2026-01-26 10:19:33 player1 plays Punctuated Equilibrium
2026-01-26 10:19:33 player1 uses Punctuated Equilibrium to make each player discard their hand and then refill their hands
2026-01-26 10:19:33 player2 randomly discards Timetraveller from hand
2026-01-26 10:19:33 player2 randomly discards Dextre from hand
2026-01-26 10:19:33 player2 randomly discards Daughter from hand
2026-01-26 10:19:33 player1 discards Bad Penny from hand
2026-01-26 10:19:33 player1 discards Urchin from hand
2026-01-26 10:19:33 player1 draws 6 cards to their maximum of 6
2026-01-26 10:19:33 player2 draws 6 cards to their maximum of 6
```

Logs for discard to amount:
```
2026-01-26 10:20:24 player1 plays Catch and Release
2026-01-26 10:20:24 player1 uses Catch and Release to return all creatures to their owner's hand and have each player randomly discard down to 6 cards
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1 randomly discards Hookmaster
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1's deck has run out of cards, so they shuffle
2026-01-26 10:20:24 player1 randomly discards Hookmaster
2026-01-26 10:20:24 player1 randomly discards Brillix Ponder
2026-01-26 10:20:24 player1 uses Brillix Ponder to draw 1 card
2026-01-26 10:20:24 player1 draws 1 card
2026-01-26 10:20:24 player1 randomly discards Hookmaster
```

There are more simultaneous ability ordering that needs to be handled - notably both players draw. Broke out a separate ticket for that since its a bunch of one-off cards. https://github.com/keyteki/keyteki/issues/4787

This also does not handle discard ordering for board wipes, etc.

### CODE REVIEW

File: server/game/GameActions/RandomDiscardAction.js [hunk 1]
```diff
@@ -1,3 +1,7 @@
+/**
```
Comment (dmikalova) [inline server/game/GameActions/RandomDiscardAction.js:1]: Refactored this to be consistent with the other new Discard*Actions. Happy to break the refactor out into a separate PR.

File: server/game/GameActions/DiscardEntireLocationAction.js [hunk 2]
```diff
@@ -0,0 +1,280 @@
...
+    }
+
+    getMultiPlayerEvent(players, context) {
+        // Create an event with a player property that passes checkEventCondition
+        // We use the first player in the list since at least one must be valid
+        return super.createEvent(
+            EVENTS.unnamedEvent,
+            { player: players[0], players, context },
+            () => {
+                // Prompt for player order
```
Comment (strib) [inline server/game/GameActions/DiscardEntireLocationAction.js]: I think it should only prompt if the user has "order simultaneous events" selected for themselves.

File: server/game/GameActions/DiscardEntireLocationAction.js [hunk 3]
```diff
@@ -0,0 +1,280 @@
...
+                    context.game.openEventWindow([discardEvent]);
+                });
+
+                context.game.queueSimpleStep(() => {
+                    discardNextCard();
+                });
+                return;
+            }
+
+            // Prompt to select next card to discard
```
Comment (strib) [inline server/game/GameActions/DiscardEntireLocationAction.js:176]: Same here.

File: server/game/GameActions/DiscardRandomCardsToAmountAction.js [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+    }
+
+    getMultiPlayerEvent(players, context) {
+        // Create an event with a player property that passes checkEventCondition
+        // We use the first player in the list since at least one must be valid
+        return super.createEvent(
+            EVENTS.unnamedEvent,
+            { player: players[0], players, context },
+            () => {
+                // Prompt for player order
```
Comment (strib) [inline server/game/GameActions/DiscardRandomCardsToAmountAction.js]: Same here.

File: server/game/GameActions/RandomDiscardAction.js [hunk 5]
```diff
@@ -36,63 +55,116 @@ class RandomDiscardAction extends PlayerAction {
...
-                        event.cards = cardsToDiscard;
-                        if (cardsToDiscard.length > 0) {
-                            context.game.addMessage(
-                                '{0} discards {1} at random',
-                                player,
-                                event.cards
-                            );
+            { player: players[0], players, context },
+            () => {
+                // Prompt for player order
```
Comment (strib) [inline server/game/GameActions/RandomDiscardAction.js]: Same here.

File: server/game/GameActions/DiscardEntireLocationAction.js (hunk 2 above)
Comment (dmikalova) [reply server/game/GameActions/DiscardEntireLocationAction.js]: Didn't even think of that! Fixed.

**Review by strib — APPROVED** [review]
