### PR TITLE
Fixes Dance of Doom when no creature is in play

### LINKED ISSUE #1450: DanceOfDoom: Invalid array length
Sentry Issue: [KEYTEKI-165](https://sentry.io/organizations/throneteki/issues/1661040023/?referrer=github_integration)

```
RangeError: Invalid array length
  File "/Users/keyteki/keyteki-node2/server/game/cards/01-Core/DanceOfDoom.js", line 9, in options
    options: context => [... Array(Math.max.apply(Math, context.game.creaturesInPlay.map(card => card.power)) + 1).keys()].
  File "/Users/keyteki/keyteki-node2/server/game/AbilityTargets/AbilityTargetOptions.js", line 18, in AbilityTargetOptions.getOptions
    options = options(context);
  File "/Users/keyteki/keyteki-node2/server/game/AbilityTargets/AbilityTargetOptions.js", line 36, in AbilityTargetOptions.hasLegalTarget
    return !!this.getOptions(context).length;
  File "/Users/keyteki/keyteki-node2/server/game/AbilityTargets/AbilityTargetOptions.js", line 29, in AbilityTargetOptions.canResolve
    return !!this.properties.dependsOn || this.hasLegalTarget(context);
  File "/Users/keyteki/keyteki-node2/server/game/baseability.js", line 147, in null.<anonymous>
    return this.nonDependentTargets.some(target => target.canResolve(context));
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by romanogit**
Fixes: KEYTEKI-165
Fixes #1450

### CODE REVIEW

File: server/game/cards/01-Core/DanceOfDoom.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ class DanceOfDoom extends Card {
             target: {
                 activePromptTitle: 'Choose a number',
                 mode: 'options',
-                options: context => [... Array(Math.max.apply(Math, context.game.creaturesInPlay.map(card => card.power)) + 1).keys()].
+                options: context => [... Array(Math.max(0, ... context.game.creaturesInPlay.map(card => card.power)) + 1).keys()].
```
Comment (cryogen) [inline server/game/cards/01-Core/DanceOfDoom.js:9]: I'm unclear on what the +1 does in this line now (Pretty unclear what it did before to be honest)

Comment (romanogit) [reply server/game/cards/01-Core/DanceOfDoom.js:9]: The Array uses the number as length, so 4, produces [0,1,2,3], but we actually want [0,1,2,3,4], so we add 1. I added the 0, ... to force Math.max to have at lease 1 value.

It is a crazy syntax. I tried it many times to believe it actually did what I wanted it to do. The javascript "..." syntax is a mistery to me.
