### PR TITLE
WoE: fix and clean up the "make a token" cards in each house

### LINKED ISSUE #3274: Clone Home not archiving properly
image

After clearing the board, I played Clone Home. Instead of archiving after making a Token, Clone Home went to my discard.

Archonimizer brings Roynsen, the Juror of Humility to The Crucible
OsramTaleka brings Heptaaura, the Beast of the Province to The Crucible
OsramTaleka won the flip and is first player
 Archonimizer has connected to the game server
 OsramTaleka has connected to the game server
Archonimizer is shuffling their deck
Archonimizer draws 6 card  s to their maximum of 6
OsramTaleka is shuffling their deck
OsramTaleka draws 6 card  s to their maximum of 6
OsramTaleka draws 1 card 
 OsramTaleka has disconnected. The game will wait up to 30 seconds for them to reconnect
 OsramTaleka has reconnected
 OsramTaleka has connected to the game server
 Archonimizer has disconnected. The game will wait up to 30 seconds for them to reconnect
 Archonimizer has reconnected
 Archonimizer has connected to the game server
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses sanctum  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Sanctum Guardian
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 1 card  to their maximum of 6
End of turn 1
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 0 Æmber  (0 keys)
TURN 1 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses brobnar  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Earthshaker
Archonimizer plays Jarl Svend
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 3 card  s to their maximum of 6
End of turn 1
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 0 Æmber  (0 keys)
TURN 2 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses ekwidon  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Trading Frenzy
OsramTaleka gains an Æmber  due to Trading Frenzy's bonus icon
OsramTaleka uses Trading Frenzy to capture 3 Æmber  from OsramTaleka, placing it on Jarl Svend
OsramTaleka plays The Old Tinker
OsramTaleka discards Generous Offer
OsramTaleka plays Auction Off
OsramTaleka gains an Æmber  due to Auction Off's bonus icon
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 4 card  s to their maximum of 6
End of turn 2
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 1 Æmber  (0 keys)
TURN 2 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Main phase - Archonimizer
Archonimizer discards Kaboom!
Archonimizer plays Braindart
Archonimizer gains an Æmber  due to Braindart's bonus icon
Archonimizer uses Braindart to do several things
Archonimizer plays Kaboom!
Archonimizer uses Kaboom! to do several things
Archonimizer plays Clone Home
Archonimizer uses Clone Home to make a token creature

### PR DESCRIPTION
**Pull request by strib**
These all need to be sequential actions, in case making a token effects the archive condition.  Clone Home (and its test) was broken.

Fixes #3274

### CODE REVIEW

File: server/game/cards/06-WoE/Muster.js [hunk 1]
```diff
@@ -8,14 +8,14 @@ class Muster extends Card {
...
-                        context.player.opponent &&
+                        !!context.player.opponent &&
                         context.player.opponent.amber > context.player.amber,
                     trueGameAction: ability.actions.archive()
                 })
             ]),
             effect: 'make a token creature{1}',
             effectArgs: (context) =>
-                context.player.opponent && context.player.opponent.amber > context.player.amber
+                !!context.player.opponent && context.player.opponent.amber > context.player.amber
```
Comment (cryogen) [inline server/game/cards/06-WoE/Muster.js:18]: This isn't really necessary. The truthy check is fine. If you really want to clean it up you can write it as `context.player.opponent?.amber > context.player.amber` but I'm not sure it gains much

File: server/game/cards/06-WoE/PressGang.js [hunk 2]
```diff
@@ -15,20 +15,20 @@ class PressGang extends Card {
         this.tracker.register(['onCardDestroyed', 'onPhaseStarted']);
 
         this.play({
-            gameAction: [
+            gameAction: ability.actions.sequential([
                 ability.actions.makeTokenCreature(),
                 ability.actions.conditional({
                     condition: (context) =>
-                        context.player.opponent &&
+                        !!context.player.opponent &&
```
Comment (cryogen) [inline server/game/cards/06-WoE/PressGang.js:22]: As above

File: server/game/cards/06-WoE/Muster.js (hunk 1 above)
Comment (strib) [reply server/game/cards/06-WoE/Muster.js]: Thanks.  I knew they weren't necessary but thought it was better style.  But I don't know anything about JS style so thanks for the info.  Done!
