### PR TITLE
Fixes Finch Cloak message

### LINKED ISSUE #2141: Finch Cloak
Is it possible for the log to be more specific about what Finch Cloak has done please?

image

### PR DESCRIPTION
**Pull request by romanogit**
Fixes #2141

### CODE REVIEW

File: server/game/cards/03-WC/FinchCloak.js [hunk 1]
```diff
@@ -18,7 +18,12 @@ class FinchCloak extends Card {
                         amount: 1
                     }))
                 ])
-            }))
+            })),
+            effect: '{1}',
+            effectArgs: (context) =>
+                context.player.amber < context.player.opponent.amber
+                    ? 'steal 1 amber'
+                    : 'gain both players 1 amber'
```
Comment (cryogen) [inline server/game/cards/03-WC/FinchCloak.js:26]: What does this message resolve to? Seems like it's missing a "make"

Comment (romanogit) [reply server/game/cards/03-WC/FinchCloak.js:26]: player1 uses Finch Cloak to gain both players 1 amber

Looks like Shakesperean english?

I can write 'to make both players gain 1 amber'

Comment (cryogen) [reply server/game/cards/03-WC/FinchCloak.js:26]: Yep that works better :)
